#ifndef DEFINICOES_H
#define DEFINICOES_H

#define TASK_TEMPO_SIZE 8000
#define TASK_DISPLAY_SIZE 3000
#define TASK_TOUCH_BTN_SIZE 1000

#define FORMAT_CALIBRATION 0
#define DEBUG_QUEUE_VALUES_AT_DISPLAY 0

#define TIME_REFRESH_DISPLAY 1000
#define TIME_REFRESH_REST_REQ 5000

#endif