#ifndef DEFINICOES_H
#define DEFINICOES_H

#define TASK_TEMPO_SIZE 8000
#define TASK_DISPLAY_SIZE 3000
#define TASK_TOUCH_BTN_SIZE 1000
#define TASK_NTP_SIZE 3000
#define TASK_FIREBASE_SIZE 8000

#define FORMAT_CALIBRATION 0
#define DEBUG_QUEUE_VALUES_AT_DISPLAY 0

#define TIME_REFRESH_DISPLAY 300
#define TIME_REFRESH_REST_REQ 10000
#define TIME_REFRESH_FIREBASE 10000
#define TIME_REFRESH_NTP 100

#endif